name: CI Retrain (MLflow Project)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt
          pip install mlflow

      - name: Run MLflow Project (local env)
        run: |
          python -m mlflow run --env-manager local MLProject -P data_dir=MLProject/hotel_bookings_preprocessing

      - name: Upload mlruns (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns